### ISSUE TITLE
Last item on chat page is hidden most times

### ISSUE THREAD

**Issue by morphis** [tim-sueberkrueb/ubuntu-hangups#13]
When entering the chat page the last item in the list is most times hidden and you need to scroll down to either see that there is one or to see it completely.

**Comment by timsueberkrueb** [comment]
Implemented a very simple workaround for now.

**Comment by morphis** [comment]
Doesn't seem to work in all cases yet. On some conversations it works on some not. Looks like this is only for the first conversation you open. All others seem to work afterwards.

**Comment by timsueberkrueb** [comment]
@morphis yeah, I need to find a better solution, thx (:

**Comment by timsueberkrueb** [comment]
This should be fixed now.

**Comment by tim-sueberkrueb** [comment]
TODO:
* [ ] Save scroll position when changing chat
* [ ] Don't auto scroll to bottom after user action
