### ISSUE TITLE
Stickers

### ISSUE THREAD

**Issue by timsueberkrueb** [tim-sueberkrueb/ubuntu-hangups#17]
Allow the user to send stickers

**Comment by timsueberkrueb** [comment]
Started working on this.
@tdryer I created a list of stickers based on the urls (see https://github.com/tim-sueberkrueb/ubuntu-hangups/blob/master/ui/stickerset.js). Can I get the `image_id` from the url in order to send a sticker with `conversation.send_message`? Thanks in advance :)

**Comment by tdryer** [comment]
I think the stickers can be loaded dynamically. The Hangouts web client seems to load an album to retrieve the list of stickers:
https://picasaweb.google.com/108618507921641169817/

It makes [this API call](https://picasaweb.google.com/data/feed/api/user/108618507921641169817?alt=json-in-script&fields=entry%5Bgphoto%3AalbumType!%3D%27ProfilePhotos%27%5D%28media%3Agroup%28media%3Athumbnail%29%2Clink%5B%40rel%3D%27http%3A%2F%2Fschemas.google.com%2Fg%2F2005%23feed%27%5D%29&callback=_callbacks_._0ihzpw00q) to do so.

**Comment by timsueberkrueb** [comment]
@tdryer cool, thank you so much! How do you find things like this oO
Will look into implementing this as soon as I find the time. Am I right that I can also get the id from this?

``` json
"gphoto$id":{
      "$t":"6089115768937826034"
 },
```

Can I pass this directly to `image_id`?

**Comment by tdryer** [comment]
That's definitely the correct ID. However, hangups fails to get a message with it for some reason:

```
Reply status code INVALID_PHOTO: Cannot find photos ([6089115768937826034]) to share for user 6f81b72873
```

This seems to be the error used whenever the ID is invalid.

**Comment by tdryer** [comment]
Looks like hangups needs to send the user ID of the photo's owner (`108618507921641169817`) as well as the photo ID.

**Comment by tdryer** [comment]
Just pushed [a change](https://github.com/tdryer/hangups/commit/18fd502a143d159b2df599b69a04d38285bb49ee) to allow specifying the user ID. Sending a sticker like this should work:

``` python
self._conversation.send_message(
    segments, image_id='6089115768937826034',
    image_user_id='108618507921641169817'
)
```

**Comment by timsueberkrueb** [comment]
@tdryer great, thank you!
![ubuntu-hangups-sticker](https://cloud.githubusercontent.com/assets/11774614/11762138/e3631f52-a0dd-11e5-87f2-6c33821bff99.png)
Done.
