### ISSUE TITLE
Improve speed

### ISSUE THREAD

**Issue by StuntsPT** [tim-sueberkrueb/ubuntu-hangups#19]
ubuntu-hangups depends on `aiohttp`, which can optionally be built with `cython` for increasing speed.
If `cython` is available, the package will be built with it, but if it's not, it will use "regular" python.
The difference in startup speed between the two implementations is staggering in tdryer/hangups , it should also make a difference here.
Probably just adding `cython` to the required packages of `ubuntu-hangups` should suffice to get a very nice speed boost (and consequently less CPU and battery usage during startup).

**Comment by tdryer** [comment]
Looks like installing cython is no longer necessary for the speed boost:
https://github.com/KeepSafe/aiohttp/commit/9243e990c693c1d881799e979cb764ab498bb9af

I'll have to update the aiohttp dependency to take advantage of this.

**Comment by tdryer** [comment]
Done here:
https://github.com/tdryer/hangups/commit/1906bce98f0549bec032deaed110c9308bef1114

**Comment by StuntsPT** [comment]
Nice! That's a warp. Thanks!
