### ISSUE TITLE
Convergence

### ISSUE THREAD

**Issue by timsueberkrueb** [tim-sueberkrueb/ubuntu-hangups#25]
Implement desktop mode.
![Screenshot](https://lh3.googleusercontent.com/-tcO-zt_VJQQ/VhVo-gCut5I/AAAAAAAAA-Y/N-bD7--ycJc/w905-h645-no/Bildschirmfoto%2Bvom%2B2015-10-07%2B20%253A47%253A41.png)

**Comment by bittner** [comment]
Wow, looks super-promising! Can't wait to see this in action!

**Comment by timsueberkrueb** [comment]
@bittner thx :) Development on this will go on here: https://github.com/tim-sueberkrueb/ubuntu-hangups/tree/feature-25

**Comment by StuntsPT** [comment]
wow

**Comment by timsueberkrueb** [comment]
In progress :)
![ubuntu_hangups_next](https://cloud.githubusercontent.com/assets/11774614/10552369/c2bc7f66-7453-11e5-97f0-dca8ca548b05.png)

**Comment by bittner** [comment]
Wow, with background picture! Looks nice!

**Comment by timsueberkrueb** [comment]
Finished :)
