### ISSUE TITLE
Rename events oddness

### ISSUE THREAD

**Issue by timsueberkrueb** [tim-sueberkrueb/ubuntu-hangups#26]
`on_event` seems not to receive any `RenameEvent`s nor `MembershipChangeEvent`s anymore.

``` python
    def on_event(self, conv_event, set_title=True, set_unread=True):
        user = self.conv.get_user(conv_event.user_id)
        if isinstance(conv_event, hangups.ChatMessageEvent):
            self.handle_message(conv_event, user, set_unread=set_unread)
        elif isinstance(conv_event, hangups.RenameEvent):
            self.handle_rename(conv_event, user)
        elif isinstance(conv_event, hangups.MembershipChangeEvent):
            self.handle_membership_change(conv_event, user)
```

@tdryer any idea?

**Comment by tdryer** [comment]
Not sure. It seems to be working on the hangups side. Anything in the log?

**Comment by timsueberkrueb** [comment]
@tdryer okay, odd, let me check again ...

**Comment by timsueberkrueb** [comment]
Okay, now that's odd: I just found out that it just doesn't work for older events. New events are handled correctly but I don't receive older ones. What I do get are some events of type `ConversationEvent`.

**Comment by tdryer** [comment]
Can you reproduce this with the hangups UI?

**Comment by timsueberkrueb** [comment]
@tdryer no, it works there, so obviously the problem's on my side ... I'm sorry, I should have tested that :)

**Comment by timsueberkrueb** [comment]
Okay, I got it. I just didn't handle rename events when loading more (older) message _facepalm_ :) Sorry @tdryer. Sometimes the problem's so trivial but you waste a lot of time because you think it lies somewhere else :/
