### ISSUE TITLE
Copying a message that contains only a link will also copy the html tags.

### ISSUE THREAD

**Issue by StuntsPT** [tim-sueberkrueb/ubuntu-hangups#27]
Which kind of defeats the purpose of being able to copy&paste a link to the browser.
Tapping on the link also does not call the browser, but that's for another issue.

**Comment by timsueberkrueb** [comment]
@StuntsPT thanks for reporting!

**Comment by StuntsPT** [comment]
I'd look into it myself, but I've been a **lot** busier than what I had anticipated... and I still have #5 on my list...

**Comment by timsueberkrueb** [comment]
fixed :)

**Comment by StuntsPT** [comment]
Thanks!
Which commit, btw? I might as well start getting familiar with the code base.

**Comment by timsueberkrueb** [comment]
@StuntsPT it's not online yet since I'm not finished with the convergence modifications. Will push both soon to the feature-25 branch.

**Comment by StuntsPT** [comment]
Cool! Thanks for the heads up.

**Comment by timsueberkrueb** [comment]
@StuntsPT it's online now: https://github.com/tim-sueberkrueb/ubuntu-hangups/tree/feature-25 :)

**Comment by StuntsPT** [comment]
Woha! Commit 9a5ff622cab9c75f5d223a6c10d69b9ab0434089 is huge!
May I suggest (and I know this is a lot about personal preference) that you make more, but smaller commits? It makes tracking changes _a lot_ easier!
That being said - was it line 20 on `ui/ChatListItem.qml` ?
Thanks!

**Comment by timsueberkrueb** [comment]
@StuntsPT yeah, you're absolutely right, it's better and easier to follow. Will try to adapt a better committing style :)

The important changes regarding this issue are: 

``` qml
// https://github.com/tim-sueberkrueb/ubuntu-hangups/blob/feature-25/ui/ChatListItem.qml#L201
MimeData {
       id: textMimeData
       color: "green"
       text: modelData.text // -> no-html text
}
```

The model now holds a html and plain-text version of the message. The html is displayed while the plain text version gets send to the clipboard when the copy action is triggered.

Relevant backend code:
- https://github.com/tim-sueberkrueb/ubuntu-hangups/blob/feature-25/backend/utils.py#L42
- https://github.com/tim-sueberkrueb/ubuntu-hangups/blob/feature-25/backend/__init__.py#L85

**Comment by StuntsPT** [comment]
Thanks! That clears it up.
