### ISSUE TITLE
Use right-arrow as send icon, paperclip for media (like Telegram)

### ISSUE THREAD

**Issue by bittner** [tim-sueberkrueb/ubuntu-hangups#3]
Currently, the application uses <img src="https://raw.githubusercontent.com/tim-sueberkrueb/ubuntu-hangups/master/media/fontawesome-paper-plane-blue.png" width="15"> as an icon for "send message".
## Replace paper plane by right-arrow

The paper plane may be confusing on Ubuntu Touch for several reasons:
1. Telegram used the paper plane as its application icon
2. Mac users know the paper plane from their mail app for sending e-mail
3. Other messengers (WhatsApp, Telegram, Viber) user a different icon for this purpose

Would it be okay if you used the same icons as [Telegram](https://uappexplorer.com/app/com.ubuntu.telegram) and [WhatsApp/Android](http://media.whatsapp.com/screenshots/Android), a thick right-arrow?
## Paper clip + popup for sending media data

Similarly, the app could use the paper clip for sending media data. (Though this is not as critical as the issue with the paper plane.) It could be nice to have the handling similar to Telegram, i.e. the paper clip opens a popup to select the type of media to attach.

**Comment by timsueberkrueb** [comment]
New logo was added, paper clip icon will be used if more media types (other than images, e.g. stickers) are supported. Thanks for reporting!
