### ISSUE TITLE
Rephrase link text in text string (Google Account Security)

### ISSUE THREAD

**Issue by bittner** [tim-sueberkrueb/ubuntu-hangups#38]
Currently "here" is used as a text for the link in a text. For usability reasons this should be changed to a text that describes the link target, as [commented  on Transifex](https://www.transifex.com/tim-sueberkrueb/ubuntu-hangups/translate/#de/ubuntu-hangupspot/68650190).

> A usability guideline suggests that instead of "here" one should use a descriptive text of the target, e.g. "... deny access in the <a ...>Security permissions</a> of your Google account."

Affected source file: [LoginScreen.qml](https://github.com/tim-sueberkrueb/ubuntu-hangups/blob/master/ui/LoginScreen.qml#L43), line 43

**Comment by timsueberkrueb** [comment]
See https://github.com/tdryer/hangups/issues/226.
