### ISSUE TITLE
Can't select text in chat

### ISSUE THREAD

**Issue by almejo** [tim-sueberkrueb/ubuntu-hangups#39]
In desktop mode I can not select text from the conversation. When trying to select the conversation moves left or right.

I know it is a convergence problem, but I am looking to this app to be the default google hangouts in ubuntu desktop

**Comment by timsueberkrueb** [comment]
@almejo you can right click on  any speech bubble and click copy for now. I'll see what I can do to make this more usable on the desktop.

**Comment by almejo** [comment]
It works great. Not if you want to copy only a bit, but works.

:D

On Tue, Jan 5, 2016 at 3:46 PM, Tim Süberkrüb notifications@github.com
wrote:

> @almejo https://github.com/almejo you can right click on any speech
> bubble and click copy for now. I'll see what I can do to make this more
> usable on the desktop.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tim-sueberkrueb/ubuntu-hangups/issues/39#issuecomment-169093988
> .

## 

Alejandro Vera
http://www.recicleta.cl

**Comment by bittner** [comment]
:+1: 

That's true. It would be nice to be able to copy parts of the text using the mouse or long-press (and selection) on touch devices.

Maybe there is a selectable attribute -- there is a [textInteractionsFlag](http://doc.qt.io/qt-5/qlabel.html#textInteractionFlags-prop) for `QLabel` -- or instead of QLabel one would have to use a [readOnly TextArea](http://doc.qt.io/qt-5/qml-qtquick-controls-textarea.html#readOnly-prop) (that would suck a bit).

**Comment by timsueberkrueb** [comment]
@bittner yeah, a readOnly TextArea is what I thought about. I'll see whether I'll find a better solution.

**Comment by almejo** [comment]
great!!!!!

On Thu, Mar 24, 2016 at 1:04 PM, Tim Süberkrüb notifications@github.com
wrote:

> Closed #39 https://github.com/tim-sueberkrueb/ubuntu-hangups/issues/39
> via 2f657f9
> https://github.com/tim-sueberkrueb/ubuntu-hangups/commit/2f657f9ebf7c9e9cc33d455ef5056bfcf0ec9d4e
> .
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/tim-sueberkrueb/ubuntu-hangups/issues/39#event-601955741

## 

Alejandro Vera
http://www.recicleta.cl
