### ISSUE TITLE
Show teaser of last message in (landscape format of) conversation list

### ISSUE THREAD

**Issue by bittner** [tim-sueberkrueb/ubuntu-hangups#46]
Currently, the list of conversations shows the user avatar and user name only. Typically, on the right side there is lots of white space that is unused.

It would be nice if the available white space could be used intelligently without cluttering the UI too much. Other messengers show
- the last message read along with the date/time information, or
- the last message sent with the status (received by server, received by destination), or
- the number of received but unread messages.

On very large smartphone screens even the chat window could be shown next to the conversation list in landscape orientation.
## Examples / Other Messengers

Just for inspiration, or to make UX consistent with the IMs on the market.
#### Gmail Layout

<img src="http://thedroidlawyer.com/wp-content/uploads/2012/11/Gmail-Screenshot.png" alt="Gmail email list with previews (teasers)">
### Telegram (Phone)

<img src="http://media2.giga.de/2014/02/telegram-screenshot1.png" alt="Telegram screenshot (smartphone)" width="50%">
### Viber (Tablet)

<img src="https://lh4.ggpht.com/igd7JuzvfvCltLswes8YFrGNbpeKVVGPl0o8l_vRbQiWPeTlYutCIIdSxV6pik7HJw=h900" alt="Viber screenshot (tablet)">
### Google Hangouts (landscape w/ chat)

<img src="http://img.talkandroid.com/uploads/2014/03/google_hangouts_screenshot-630x393.png" alt="Google Hangouts screenshot (landscape w/ chat)">

**Comment by timsueberkrueb** [comment]
@bittner thanks for the suggestion and the detailed description!
