### ISSUE TITLE
Lessons learned from implementing Hangups

### ISSUE THREAD

**Issue by bittner** [tim-sueberkrueb/ubuntu-hangups#55]
(This is not really an issue but more a question that me and maybe other people may be interested in.)

Tim, I'd be interested in the lessons learned from
- implementing a **native app** on Ubuntu Touch with **Python**,
- also catering **convergence** when convergence is not yet fully available on the desktop.
- What is the setup like of your **development environment**,
- do you use any specific tools, and
- what does testing and **deployment** look like.

_Bonus question:_ One of the, I believe, yet unsolved issues for an app really feeling "native" is offline functionality. How hard is this to tackle? 

I'm looking into implementing a chat app with Slack's [Real-Time Messaging API](https://api.slack.com/rtm), so I wonder is this something that can be done in a couple of days, or more realistically weeks or months?

**Comment by timsueberkrueb** [comment]
Hey, nice to hear from you :)
Hangups is not the only app I implemented with QML and **Python** and I got to really like this combination. You probably know that most native Ubuntu apps are using C++ as a backend and it depends on more than one thing whether it makes sense to choose Python instead. In my case, there was this awesome Hangups already existing which actually got me to the idea of creating an app for Ubuntu Touch, so the choice of Python was obvious :) For other use cases it might be worth to taking a look at C++/pure JavaScript though. 
It's not very hard to **port** an app using PyOtherSide to Ubuntu Touch. You just need to fetch the pyotherside packages (which I'm doing using the [get_libs.py](https://github.com/tim-sueberkrueb/ubuntu-hangups-lib/blob/master/get_libs.py).
Implementing **convergence** features is most about (responsive) design. You basically just need to test the app on the desktop with different window sizes to make sure it looks good on whatever form-factor. Some features are not available on Unity 7 desktop, but the combination of phone and desktop **testing** works fine here (it will be a better experience in the future with Unity 8 though).
Essential for my **development environment** are Ubuntu SDK (Qt Creator) and PyCharm for writing code in C++/Qt/QML and Python respectively. As a **tool** I really can recommend  [qmllive workbench](https://github.com/Pelagicore/qmllive).
**Deployment** is very easy with the Ubuntu SDK and the script I mentioned above.
It really depends on your specific application how hard it is to implement offline functionality. In case of Hangups I'm awaiting upstream changes, the rest should be trivial.
I'd love to see a native Slack client on Ubuntu Touch (please do it :))! Your last question really depends on the **time** you can spend on the project. Writing a messanger, even if you're just going to implement the platform specific and user interface side (as I did with Hangups), it is not something you'd do in a couple of days (at least not for me), it took me some weeks to get to a working state (I spend a chunk of my last summer holidays on it :)). But this might also depend on other things like skills in the chosen frameworks/programming languages for example. I was actually still learning developing with the Ubuntu Toolkit/QML in general at that time while I already had knowledge in Python.

**Comment by bittner** [comment]
Just a quick follow-up re 

> "... it might be worth to taking a look at C++/pure JavaScript ..."

Is bundling Python with an Ubuntu Touch application just plain overhead? In a sense that _"if you're comfortable with JavaScript use it instead of Python"_?

I wouldn't use C++ just because other languages are less error prone (think of memory leaks). And with Python code would be both faster and have a smaller source code footprint (which typically translates to "less bugs").

**Comment by timsueberkrueb** [comment]
@bittner The only downside is that you will be shipping the Python plugin and environment besides your application which makes it a bit heavier (Hangups click package is about ~9MB). 
The rest really only depends on your personal preferences and your use case.
