### ISSUE TITLE
Python issues on launch -- Ubuntu Touch 15.04

### ISSUE THREAD

**Issue by RealJohnGalt** [tim-sueberkrueb/ubuntu-hangups#56]
Hello, I am unable to run the current version of ubuntu-hangups on the current (or slightly older) ubuntu touch stable or rc-proposed. Here are all the errors: https://imgur.com/a/XSx3v

Any ideas? Someone in #ubuntu-touch said the issue's that your application isn't bundling python (which doesn't seem right to me, though I don't know much about ubuntu touch).

Thank you for the promising looking app :+1:

**Comment by timsueberkrueb** [comment]
@RealJohnGalt Which device are you using? My guess is that it's the One Plus One?
In this case, it's a known issue: Hangups is shipping with it's own Python installation using [PyOtherSide](http://pyotherside.readthedocs.org/). But there is also a system-specific python installation that comes with Ubuntu Touch. Normally, the application confinement on Ubuntu doesn't allow apps to access it. On the OPO though, AppArmor is unfortunately not fully implemented yet. This results in the app getting confused with the system python installation. I tried to fix it yesterday by simply removing the relevant paths from `sys.path` but oddly PyOtherSide then wasn't able to find the modules I'm shipping with (even though the paths of those were still there) which I can't yet explain to myself. I might look into this again.
However, the proper solution for this is to properly integrate AppArmor with the OPO which is up to the porter.

**Comment by RealJohnGalt** [comment]
I'm using the nexus 5 (hammerhead) with ubuntu touch right now. Apparmor makes sense (I was thinking it was a selinux issue, then realized selinux isn't used in utouch like I thought).

I'll look into fixing the apparmor patches based on an official device. Thank you for the detailed explanation.

**Comment by RealJohnGalt** [comment]
I fixed the issue for hammerhead. Thank you again for your time and help.

**Comment by zubozrout** [comment]
@RealJohnGalt I am very sorry for the off-topic, but are you using Vojtěch Boček's tasemnice.eu repository or your custom builds? For Nexus 7 deb his server sopped working recently because the keyring has expired and when I tried to build it myself I got stuck at the point of uploading my custom image to the device. I have been able to complete all the steps up to the last when it seems to freeze upon writing system image to the device itself. Did you experience the same issues on your device? Thank you in advance for your answer.

**Comment by timsueberkrueb** [comment]
@RealJohnGalt wow, cool, that was fast :)

**Comment by RealJohnGalt** [comment]
@zubozrout You need to either set your clock back before the 23rd of Feb, or find a different server. For hammerhead, I'm using the ubports server (with working OTA). It doesn't look like deb or flo are supported by ubports, so you're probably stuck with the clock workaround.

**Comment by zubozrout** [comment]
@RealJohnGalt Thank you very much for the info. Sadly, I don't think this will help me substantially ... as I fear that the tasemnice.eu server is broken as well so I would be stuck with the February's version and won't be able to install anything newer. And Vojtěch Boček is ignoring me for quite some time now ... probably pushed me to the spam folder. When I have more time I'll try to ask on IRC for some more info on creating a new device port - especially for some details on the last step.
PS. Wow, I didn't know this site https://devices.ubports.com/ ... love this project :).

**Comment by stevenandree** [comment]
@RealJohnGalt having similar issue with Nexus 5. If you have the time, would you mind sharing your fix. Cheers

**Comment by zippynk** [comment]
I second this - @RealJohnGalt, it would be great if you could share your solution. I am running Ubuntu Touch on a Nexus 5 as well and am having the same issue (UBPorts images).

**Comment by timsueberkrueb** [comment]
Hey @RealJohnGalt, I know that the Ubports developers are struggling with the Apparmor implementation for some devices right now. It would be awesome if you could reach them out and share your solution, when you have the time. I'm sure everyone would really appreciate it!

**Comment by MartijnBraam** [comment]
I'm using the nexus 5 hammerhead with the latest ubuntu touch version which is listed as supporting apparmor. I still get a lot of importerrors when starting the app.

**Comment by timsueberkrueb** [comment]
Hey @MartijnBraam. I apologize for the late response, I was on vacation.
I was told that it works fine now on `devel_rc-proposed` while it is not supported on the stable channel, yet.

**Comment by MartijnBraam** [comment]
Ok then I'll wait a bit
