### ISSUE TITLE
Move translations to Transifex

### ISSUE THREAD

**Issue by bittner** [tim-sueberkrueb/ubuntu-hangups#6]
We should manage our i18n efforts (translations) on Transifex, which is free for Open Source projects. Simply open an account at [transifex.com](https://www.transifex.com/), add the project, and upload the translations resources.

For developers there's the Python-powered [Transifex client](http://docs.transifex.com/client/), a command line tool to extract and upload translation resources.

**Comment by timsueberkrueb** [comment]
Great, it's now online: https://www.transifex.com/tim-sueberkrueb/ubuntu-hangups/

**Comment by bittner** [comment]
Awesome! :+1:
