### ISSUE TITLE
Google Voice conversations show with their conversation ID rather than their source.

### ISSUE THREAD

**Issue by ShadowEO** [tim-sueberkrueb/ubuntu-hangups#65]
First, let me say that this app is absolutely wonderful on my Nexus 7. Huge Boon. I'm also not sure if this actually can be fixed since there's no official Hangouts API (unless I'm mistaken), it's entirely possible that Google is just querying the GV account for this in their clients.

And now to my bug report, I can see Google Voice conversations in the list (as I can on android and in the web) however they appear to be named with their conversation IDs rather then a friendly name like normal conversations (their phone numbers in this case).

So while I can see my Hangouts SMS and Voicemail transcriptions, I'm not entirely sure who they're actually from.

**Comment by timsueberkrueb** [comment]
Hey @ShadowEO.
According to this bug https://github.com/tdryer/hangups/issues/52 they actually show up as phone numbers in upstream Hangups. Can you confirm this?

**Comment by ShadowEO** [comment]
I just opened the latest version of hangouts available through the store (as I don't yet have the time to build the current tree's click package), but I can confirm that while they no longer show up with conversation IDs, they do all show Unknown, even in the About Conversation window. I can grab you screenshots or logs if you wish, just let me know what you need and I'll pull them from my UTouch device.

EDIT: I did compile and install the HEAD revision here using the Ubuntu SDK, and the behavior still happens under Hangups, only rather than their numeric conversation IDs, it shows as Unknown (as previously stated with the Ubuntu Store version)

**Comment by ShadowEO** [comment]
Tim,

My apologies, I just realized what you were asking ^_^; Sorry, have had a very "slow" day today.

Yes, The conversations show properly in upstream Hangups and appear with their numbers as the identifiers.

**Comment by timsueberkrueb** [comment]
@ShadowEO no problem, thanks for the information.

**Comment by ShadowEO** [comment]
This is fixed in the newest release of Hangups available on the Ubuntu Store! Thanks!
