### ISSUE TITLE
Can't launch from App Scope (OTA-13)

### ISSUE THREAD

**Issue by zubozrout** [tim-sueberkrueb/ubuntu-hangups#66]
Hello,
In the last few weeks I've noticed several times that launching Hangups is not possible. So far I've only seen this behaviour occur using the desktop icon in the app scope and a little bit less often in the app details screen. Launching hangups from the left Unity panel has always worked for me.

This is an odd behaviour and I suspect it may not really be app related. I've seen the exact oposite with Telegram app not launching fron the left panel.

Both Telegram (rarely) and Hangups (usually) ordinarily behaves this way after the app has been already launched, albeit today I wasn't able to launch Hangups at all.

It may be worth noting that I am running rc-proposed channel and just recently did a complete reinstall and wipe of my Meizu MX4 (it happened before and still happens now)

Any idea what may be going on there? Thank you very much :)

**Comment by timsueberkrueb** [comment]
Hey @zubozrout, that's this bug: https://bugs.launchpad.net/ubuntu/+source/url-dispatcher/+bug/1591342
I hope it's going to be fixed soon.

**Comment by zubozrout** [comment]
Thanks :)

**Comment by timsueberkrueb** [comment]
Reopening this. The issue has not been fixed, yet and OTA 13 was released today.
This means that users on the stable channel will now start running into this.

**Comment by StuntsPT** [comment]
Just got hit by this after the update to OTA13.
Is there a known workaround?

**Comment by timsueberkrueb** [comment]
@StuntsPT hey. You can still launch the app from the launcher.
If you have not pinned it to the launcher, run

```
ubuntu-app-launch ubuntu-hangups.timsueberkrueb_ubuntu-hangups.timsueberkrueb_0.3.3.1
```

from the terminal and make sure to pin it :)

**Comment by anupam207** [comment]
@tim-sueberkrueb 
`ubuntu-app-launch ubuntu-hangups.timsueberkrueb_ubuntu-hangups.timsueberkrueb_0.3.3.1` gives an 
`Unable to find keyfile for application 'ubuntu-hangups.timsueberkrueb_0.3.3.1'` warning only, app doesn't start.

**Comment by anupam207** [comment]
My device is E5, stable channel, OTA-13.

**Comment by bittner** [comment]
There is a change in the file system that may be related to this issue (I'm just guessing).

> [OTA-13 on BQ E4.5 moved click software to read-only file system /custom](https://lists.launchpad.net/ubuntu-phone/msg22403.html) (Matthias Apitz)

**Comment by timsueberkrueb** [comment]
@bittner this is unlikely, but thanks for the information.
Fix coming soon.

**Comment by bittner** [comment]
I've taken a look at the Desktop file `/home/phablet/.local/share/applications/ubuntu-hangups.timsueberkrueb_ubuntu-hangups.timsueberkrueb_0.3.3.1.desktop` and at the folder `/opt/click.ubuntu.com/.click/users/phablet/ubuntu-hangups.timsueberkrueb/` on my phone, and it seems to be all regular (apart from the fact that all files have the permissions set to "executable", as always when files come from a Microsoft Windows environment).

Is there any logfile to find out what's wrong? Something where `aa-exec-click` writes messages to?

**Comment by timsueberkrueb** [comment]
Update which works around this bug was published to the store.

**Comment by StuntsPT** [comment]
Great work!
It required a reboot, but the fix worked.
Thanks!

**Comment by timsueberkrueb** [comment]
@StuntsPT thanks for the info. Make sure not to logout because of #68 😓

**Comment by StuntsPT** [comment]
Yeah, #68 is turning out to be a real headache for the whole hangups project. But since some workarounds have been found, I'd say a definite fix should be available soon.
Anyway, that's a good heads-up for anyone else reading this.
