### ISSUE TITLE
Part of the message may not be sent using the send button, enter works probably fine

### ISSUE THREAD

**Issue by zubozrout** [tim-sueberkrueb/ubuntu-hangups#8]
Hi,
I've noticed that sending messages using the send button may leave part of the message in the text field and sending only the beginning.

So for example if I type: "Something really long" ... using the send button next to the text field may send only "Something really" ... while keeping "long" in the text field and not sent.

This is not easily reproducible ... it mostly works just fine, but I've seen this behaviour twice already.
Any idea what may be causing this?

Also, I can't say enter works, it is jut that I haven't seen it happen using it yet.

Thank you

**Comment by timsueberkrueb** [comment]
@zubozrout this is probably caused by the auto correction (the last underlined word doesn't count as text in the TextField). I'm using a workaround for this: it hides the OSK before sending which adds the underlined word to the TextField's text.

**Comment by zubozrout** [comment]
@tim-sueberkrueb Ok, that is interesting. Thanks for the info.

**Comment by ahoneybun** [comment]
I'll confirm I'm having the same issue and that is is not easy to reproduce as well. Thanks for the heads up Tim!

**Comment by sverzegnassi** [comment]
You may want to have a look at http://doc.qt.io/qt-5/qinputmethod.html#commit
Call the commit() function when the "send" button is clicked, so that the uncommit text (the one underlined by the predictive feature) is properly commited into the TextField.
This should fix the issue.

Thanks for your app, it's really a great addition to the Ubuntu Store!

**Comment by timsueberkrueb** [comment]
@sverzegnassi wow, thanks!

**Comment by sverzegnassi** [comment]
Oops, I forgot some bit... in order to call it from QML, the code is:
`Qt.inputMethod.commit()`

Ref. http://doc.qt.io/qt-5/qml-qtqml-qt.html#inputMethod-prop

@tim-sueberkrueb You're welcome, and thanks again for this app!
